### ISSUE TITLE
Question about Token Storage patch

### ISSUE THREAD

**Issue by THWLF** [GirlInTheShell/Lunia#1]
Hi, I already asked this on the here linked Reposetory but it seems the repo is dead over there.

I just stumbled over your repository and read that there is also a Token Storage Patch next to a few other , but I didnt found anything about it.

Is there any news or update about it?

**Comment by TheSolSys** [comment]
Oh hey, yea sorry, life got very complicated and all work on coding
projects have largely been on hold for a few years now.

Yes, there are a lot of features to this extension of the Lua language, but
they're not available currently. I do plan to release the language at a
future point still, but do not have any way to estimate when. Sorry,
sometimes life can be very terrible.

**Comment by THWLF** [comment]
I totally understand, thanks for the Answer.
